# -*- coding: utf-8 -*-
"""Sab_ hello_world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/GisstHubana/da0e5f27601d1004322ccc203d91bb7e/sab_-hello_world.ipynb
"""

print("hello world")

"""Hier mal Sabines Weltansicht ;)

"""

print("Hallo Berlin")

#neuer Versuch
print("nun ohne alles zu überschreiben")